# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22fdba1119d68fab814c2662a6b762950544721e6c650ab102c3b3554d9d3ab5e1a79c4f8ed28db5c38f732b34941b6b611d07302bc1856f122d3c88c3e66893

test:
  secret_key_base: c93818f1cc429b13a7b8bf741475d6207fff52aba38496cff62ca4ad972f5c6178ef8651e2c91bcb98b01aa1da7ead93b8f80b7a63f63340b86945e2d2a2ea2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
